context:
  name: rocm-core
  version: "7.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: "https://github.com/ROCm/rocm-systems/archive/refs/tags/rocm-${{ version }}.tar.gz"
    sha256: a700912d102b35c9336b7352d09d56b9d19e4957daf53779983c3d00ce744c9d

build:
  number: 0
  skip: not (linux or win)
  script:
  - if: win
    then: |
      cd projects/rocm-core
      mkdir build
      cd build
      cmake -GNinja ^ 
       -S %CD%.. -B . ^
      -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
      -DROCM_VERSION="${{ version }}" 
      ninja install
  - if: linux
    then: |
      cd projects/rocm-core
      mkdir build
      cd build
      cmake -GNinja \
      -S $PWD/../ -B . \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      -DROCM_VERSION="${{ version }}" 
      ninja install


requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake
    - ninja
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}

tests:
  - requirements:
      run:
        - cmake-package-check
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
    script:
      - cmake-package-check rocm-core
  - package_contents:
      include:
        - rocm-core/rocm_version.h
      lib:
        - rocm-core

about:
  homepage: https://github.com/ROCm/rocm-systems
  license: MIT
  license_family: MIT
  license_file: 
    - projects/rocm-core/LICENSE.md
  repository: https://github.com/ROCm/rocm-systems/projects/rocm-core
  summary: "ROCm core package"

extra:
  recipe-maintainers:
    - traversaro
    - isuruf
